name = "Neoforge 21"
author = "Sea Jr."
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "20a9f7a4585355d103d212ff03cec5179df42421b76e32202a1067947fb08670"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.77"

[options]
acceptable-game-versions = ["1.21.0", "1.21.1", "1.21.x", "1.21"]
