name = "Neoforge 21"
author = "Sea Jr."
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "65e454bbea47381287e4345fc4e4597e0836476367e2db8807c94b286e965a63"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.86"

[options]
acceptable-game-versions = ["1.21.0", "1.21.1", "1.21.x", "1.21"]
