name = "Neoforge 21"
author = "Sea Jr."
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "52b7122b81d21413d55d282fb57c2766057a8d983d7607514bcaa2c1a7f6267d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.77"

[options]
acceptable-game-versions = ["1.21.0", "1.21.1", "1.21.x", "1.21"]
