name = "Neoforge 21"
author = "Sea Jr."
version = "1.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a56aaf64d51c2074d59aebc237c169cff6f408fcb0a0670b3abc168ace3ea5be"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.77"

[options]
acceptable-game-versions = ["1.21.0", "1.21.1", "1.21.x", "1.21"]
