[general]
giveJournal = true
holdToCast = true
doMinigame = false
showUnread = true
showToasts = true
minigameDifficulty = 1.0
rodDurabilityMultiplier = 1.0
defaultLineColor = false
hideUnknownFishNames = true
baseCrateRarity = 20
[worldgen]
disableFishingBoat = false
